version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    depends_on:
      - tomcat
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network

  tomcat:
    image: tomcat:latest
    ports:
      - "8081:8080"
    networks:
      - app-network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    ports:
      - "3306:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
