---
# This playbook removes Apache (apache2) from Ubuntu servers

- name: Remove Apache from Ubuntu
  hosts: webservers
  become: yes

  tasks:
    - name: Stop Apache service if running
      service:
        name: apache2
        state: stopped
        enabled: no   # Prevent Apache from starting on boot

    - name: Remove Apache package
      apt:
        name: apache2
        state: absent
        purge: yes    # Remove config files too

    - name: Remove custom index.html (optional)
      file:
        path: /var/www/html/index.html
        state: absent

    - name: Remove Apache configuration file (optional)
      file:
        path: /etc/apache2/apache2.conf
        state: absent

    - name: Remove entire Apache directory (optional and aggressive)
      file:
        path: /etc/apache2
        state: absent
        recurse: yes
