---
- name: Uninstall Java and Maven on Ubuntu and Amazon Linux servers
  hosts: all
  become: yes

  tasks:
    - name: Uninstall Java and Maven on Ubuntu
      apt:
        name:
          - openjdk-11-jdk
          - maven
        state: absent
        autoremove: yes
      when: ansible_facts['os_family'] == 'Debian'

    - name: Uninstall Java and Maven on Amazon Linux
      yum:
        name:
          - java-11-amazon-corretto-devel
          - maven
        state: absent
      when: ansible_facts['os_family'] == 'RedHat'
